[package]
name = "async-graphql-interfaces"
version = "0.0.0"
authors = ["Blaine Bublitz <blaine.bublitz@gmail.com>"]
edition = "2018"

[[bin]]
name = "sample"
path = "src/main.rs"

[dependencies]
async-graphql = "1.9.0"
tokio = { version = "0.2", features = ["macros"] }
